# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo_db
    image: mongo
    ports: 
      - "27017:27017"
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: daniel
      MONGO_INITDB_ROOT_PASSWORD: work#0911

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example